/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import javax.swing.JOptionPane;
import Modelo.Cola;


/**
 *
 * @author GERSO
 */
public class Lista extends javax.swing.JFrame {

    Cola co= new Cola();
    int n=1;
    int c=1;
    
    public Lista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtDpi = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        rbRetiro = new javax.swing.JRadioButton();
        rbCheque = new javax.swing.JRadioButton();
        rbDeposito = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        taHistory = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        taCaja1 = new javax.swing.JTextArea();
        txtAge = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        taCaja2 = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        taCaja3 = new javax.swing.JTextArea();
        btnInsertar1 = new javax.swing.JButton();
        btnCaja1 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setPreferredSize(new java.awt.Dimension(779, 800));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel4.setText("Banco Nacional de Guatemala");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel2.setText("DPI");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel3.setText("Nombre y apellido");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel5.setText("Edad");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 90, -1, -1));
        getContentPane().add(txtDpi, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 182, 28));
        getContentPane().add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, 230, 28));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        jLabel1.setText("Transaccion(es) a realizar");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, -1, -1));

        rbRetiro.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        rbRetiro.setText("Retiro");
        getContentPane().add(rbRetiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 220, -1, -1));

        rbCheque.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        rbCheque.setText("Cheque");
        getContentPane().add(rbCheque, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 220, -1, -1));

        rbDeposito.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        rbDeposito.setText("Deposito");
        getContentPane().add(rbDeposito, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, -1, -1));

        taHistory.setEditable(false);
        taHistory.setColumns(20);
        taHistory.setRows(5);
        jScrollPane1.setViewportView(taHistory);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 354, 310, 390));

        taCaja1.setEditable(false);
        taCaja1.setColumns(20);
        taCaja1.setRows(5);
        jScrollPane4.setViewportView(taCaja1);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 360, 230, 100));
        getContentPane().add(txtAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 130, 86, 28));

        taCaja2.setEditable(false);
        taCaja2.setColumns(20);
        taCaja2.setRows(5);
        jScrollPane5.setViewportView(taCaja2);

        getContentPane().add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 500, 230, 100));

        taCaja3.setEditable(false);
        taCaja3.setColumns(20);
        taCaja3.setRows(5);
        jScrollPane6.setViewportView(taCaja3);

        getContentPane().add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 631, 230, 100));

        btnInsertar1.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        btnInsertar1.setText("Ingresar");
        btnInsertar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertar1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnInsertar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 280, 118, 49));

        btnCaja1.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        btnCaja1.setText("Siguiente");
        btnCaja1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCaja1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnCaja1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 530, 118, 49));

        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        jButton1.setText("Finalizar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 670, 110, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInsertar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertar1ActionPerformed
        int time = 0;
        taHistory.setText(null);
        //Definir Tiempo y sacar el mas alto
        if(rbDeposito.isSelected() == true){
            time = time + 10;
        }
        if(rbRetiro.isSelected() == true){
            time = time + 15;
        }
        if(rbCheque.isSelected() == true){
            time = time + 20;
        }
        co.recorrerMayor(time);
        
        
        int d, e;
        String nom;
        nom = txtName.getText();
        e = Integer.parseInt(txtAge.getText().trim());
        d = Integer.parseInt(txtDpi.getText().trim());
        if(e >= 60){
            co.insertarInicio(n, c, d, nom, e, time);
            co.insertarInicio1(n, c, d, nom, e, time);
            taHistory.append(co.mostrar());
        }else{
            co.insertar(n, c, d, nom, e, time);
            co.insertar1(n, c, d, nom, e, time);
            taHistory.append(co.mostrar());
        }
        n++;
        c++;
        //limpieza
        txtName.setText("");
        txtAge.setText("");
        txtDpi.setText("");
        rbDeposito.setSelected(false);
        rbRetiro.setSelected(false);
        rbCheque.setSelected(false);
    }//GEN-LAST:event_btnInsertar1ActionPerformed

    private void btnCaja1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCaja1ActionPerformed
        
        if(co.colaVacia() == true){
            JOptionPane.showMessageDialog(null, "Cola vacia");
        }else{
            co.recorrer2();
            taHistory.setText(null);
            taHistory.append(co.mostrar());
        }
    }//GEN-LAST:event_btnCaja1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        co.recorrer();
    }//GEN-LAST:event_jButton1ActionPerformed
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCaja1;
    public javax.swing.JButton btnInsertar1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    public javax.swing.JRadioButton rbCheque;
    public javax.swing.JRadioButton rbDeposito;
    public javax.swing.JRadioButton rbRetiro;
    public static javax.swing.JTextArea taCaja1;
    public static javax.swing.JTextArea taCaja2;
    public static javax.swing.JTextArea taCaja3;
    public javax.swing.JTextArea taHistory;
    private javax.swing.JTextField txtAge;
    public javax.swing.JTextField txtDpi;
    public javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
